#!/bin/bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

# 停止节点运行
pkill geth

sleep 1

# 删除区块链
rm -r $DIR/data/

sleep 1

# 节点重新运行
$DIR/geth --dev --rpcport 8546 --rpc --rpccorsdomain "*" --datadir "$DIR/data" \
--rpcapi "personal,db,eth,net,web3"&

sleep 2

exit 0
