#!/usr/bin/env bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}")" && pwd )";

nohup ./geth --dev --mine --rpc --rpcaddr 127.0.0.1 --port 10071 --rpcport 10070 --rpcapi "personal,db,eth,net,web3" --datadir "$DIR/data" &
