var account = require("./Account")
account.createNewAccount("king").then(console.log).catch(console.log)
account.createNewAccount("king").then(console.log).catch(console.log)
account.createNewAccount("king").then(console.log).catch(console.log)
account.createNewAccount("king").then(console.log).catch(console.log)
account.createNewAccount("king").then(console.log).catch(console.log)
account.createNewAccount("king").then(console.log).catch(console.log)
