#!/usr/bin/env bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

BIN=$DIR/bin

#无限循环每隔一秒自动生成一个区块
while [ 1 -le 2 ]
do
    $BIN/litecoin-cli -regtest -conf=$DIR/bitcoin.conf -datadir=$DIR/data generate 1
    sleep 1m
done
