# 数据库相关
mongodb:
  host: mongodb://localhost:27017/tinypay_ropsten

ethereum:
  host: 127.0.0.1
  rpcport: 8545
  wsport: 8546
  available_currency_alias:
    - ether
    - king
    - tiny
  confirmations: 20
  mainAccount:
    "0xee6a7a60f2f8d1e45a15eebb91eec41886d4fa08"
  mainPrivateKey:
    "0xe78dd8f82f884b144381fa7c722fdef191273b8955306cf0129ff8b80c5390c6"

ether:
  category: ether
  name: ether
  symbol: ether
  gasPrice: "4000000000"
  gas: "100000"
  startHeight: 3243656
  autoSendBack: true

king:
  contractAddress: "0x53565FEbe212Fc43392Fdf01aE19CCd3d492695A" #合约地址
  category: erc20           #token类别
  symbol: KING(KingCoin)    #token缩写
  name: KingCoin            #token名称
  gasPrice: "4000000000"      #交易预定gasPrice
  gas: "100000"               #交易预定gaslimit
  startHeight: 3243656     #起始高度
  autoSendBack: true       #是否自动转回主账户（ehtereum.mainAccount）
  sendBackNeededGas: "50000"

tiny:
  contractAddress: "0x485f659412636c389d6C7E6E9e10916C7A3BBe5d"
  category: erc20
  symbol: TINY
  name: Tiny Calf
  gasPrice: "4000000000"
  gas: "100000"
  startHeight: 3243656
  autoSendBack: true
  sendBackNeededGas: "50000"


www:
  port: 1990
  disableVerify: true
  # appkey: b172afe6dc6fecc491bdb458853eeac49bd2a930
  # appsecret: 997abe175d48da23af5699fe668f89e57fbc49fbcaa3ac1970b23aca9d3168a6
  callbackUri: http://192.168.1.107:3000/user/SEND_RECHARGE_ORDER
