#!/usr/bin/env node
var crypto = require("crypto")
var program = require('commander');

program
  .usage(`-n yuce`)
  .option('-n, --name [name]', 'name of the APP')
  .parse(process.argv);


var appname = program.name.toString()

var sha1 = crypto.createHash('sha1')
sha1.update(appname + "tinypay");
var appkey = sha1.digest('hex')

var sha256 = crypto.createHash('sha256');
sha256.update(appname + "tinypay" + Date.now());
var appsecret = sha256.digest('hex')

console.log(`${appname}'s secret has been generated:
  appkey    :     ${appkey}
  appsecret :     ${appsecret}`)
