#!/usr/bin/env bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

BIN=$DIR/bin

while [ 1 -le 2 ]
do
    $BIN/bitcoin-cli -regtest -conf=$DIR/bitcoin.conf -datadir=$DIR/data generate 1
    sleep 1m
done
