#!/usr/bin/env bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

BIN=$DIR/bin

# 停止节点运行
$BIN/bitcoin-cli -regtest -conf=$DIR/bitcoin.conf -datadir=$DIR/data stop

sleep 2

# 删除前区块链数据
rm -r $DIR/data/regtest

sleep 1

#
$BIN/bitcoind -regtest -conf=$DIR/bitcoin.conf -datadir=$DIR/data -daemon

sleep 3

# 预挖矿200个
$BIN/bitcoin-cli -regtest -conf=$DIR/bitcoin.conf -datadir=$DIR/data generate 200
